repos:
  # Schnelle Qualitätschecks für alle Dateien (nur manuell)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Ruff: Lint + (bei Bedarf) Fixes (nur manuell)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  # Black: Formatter (nur manuell)
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black

  # mypy: statische Typprüfung (nur manuell)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies:
          - sqlalchemy>=2
          - pydantic>=2
          - types-requests
          - types-python-dateutil
          - types-PyYAML

  # (Optional) Pyproject-Formatierung (nur manuell)
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.6.0
    hooks:
      - id: pyproject-fmt

  # (Optional) Lokaler Pytest-Hook – jetzt ebenfalls nur manuell
  - repo: local
    hooks:
      - id: pytest-on-push
        name: Run pytest (manual)
        entry: bash -c 'pytest -q'
        language: system
        pass_filenames: false
        # keine stages -> greift nur bei manueller Ausführung

# WICHTIG: Standard-Stage ist jetzt 'manual' – es läuft nichts automatisch bei commit/push.
default_stages: [manual]
