"""create items table

Revision ID: 21a22a432189
Revises:
Create Date: 2025-08-27 13:50:59.427545
"""

from typing import Sequence, Union, TYPE_CHECKING

import sqlalchemy as sa
from alembic import op  # type: ignore[attr-defined]

if TYPE_CHECKING:
    # Nur für mypy: `op` ist ein Laufzeit-Proxy auf Alembic-Operations.
    from alembic.operations import Operations as AlembicOperations

    _: AlembicOperations  # noqa: F401  (nur für Typchecker, kein echtes Symbol)

# revision identifiers, used by Alembic.
revision: str = "21a22a432189"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_items_id"), "items", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_items_id"), table_name="items")
    op.drop_table("items")
    # ### end Alembic commands ###
