"""create maintenances table

Revision ID: 2ce877b154d4
Revises: 9fbd8abc4b70
Create Date: 2025-09-09 11:09:06.995292
"""

from typing import Sequence, Union, TYPE_CHECKING

import sqlalchemy as sa
from alembic import op  # type: ignore[attr-defined]

if TYPE_CHECKING:
    from alembic.operations import Operations as AlembicOperations

    _: "AlembicOperations"  # noqa: F401  (nur für Typchecker, kein echtes Symbol)

# revision identifiers, used by Alembic.
revision: str = "2ce877b154d4"
down_revision: Union[str, Sequence[str], None] = "9fbd8abc4b70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "maintenances",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bike_id", sa.Integer(), nullable=False),
        sa.Column("performed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_external", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("vendor", sa.String(length=200), nullable=True),
        sa.Column("cost", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("mileage_km", sa.Integer(), nullable=True),
        sa.Column("duration_min", sa.Integer(), nullable=True),
        sa.Column("warranty", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["bike_id"], ["bikes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_maintenances_bike_id"), "maintenances", ["bike_id"], unique=False)
    op.create_index(op.f("ix_maintenances_id"), "maintenances", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_maintenances_id"), table_name="maintenances")
    op.drop_index(op.f("ix_maintenances_bike_id"), table_name="maintenances")
    op.drop_table("maintenances")
    # ### end Alembic commands ###
