"""create bikes table

Revision ID: 9fbd8abc4b70
Revises: 3d2181db1770
Create Date: 2025-09-08 08:43:54.309272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fbd8abc4b70'
down_revision: Union[str, Sequence[str], None] = '3d2181db1770'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bikes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('color', sa.String(length=60), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('frame_number', sa.String(length=120), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('weight_kg', sa.Integer(), nullable=True),
    sa.Column('brake_type', sa.String(length=60), nullable=True),
    sa.Column('tire_size', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'frame_number', name='u_owner_frame')
    )
    op.create_index(op.f('ix_bikes_id'), 'bikes', ['id'], unique=False)
    op.create_index(op.f('ix_bikes_owner_id'), 'bikes', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bikes_owner_id'), table_name='bikes')
    op.drop_index(op.f('ix_bikes_id'), table_name='bikes')
    op.drop_table('bikes')
    # ### end Alembic commands ###
